[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
requires-python = ">=3.9"
name = "nsls2ptycho"
description = "NSLS-II Ptychography Software"
authors = [
    { name = "Leo Fang" },
    { name = "Zirui Gao" },
    { name = "Sungsoo Ha" },
    { name = "Zhihua Dong" },
    { name = "Xiaojing Huang" , email = "xjhuang@bnl.gov" }
]
readme = "README.md"
license-files = ["LICENSE"]
dynamic = ["version"]

[project.urls]
Homepage = "https://github.com/NSLS2/ptycho_gui"

[project.scripts]
run-ptycho = "nsls2ptycho.ptycho_gui:main"
run-ptycho-backend = "nsls2ptycho.core.ptycho.recon_ptycho_gui:main"
run-ptycho-worker = "nsls2ptycho.remote_worker:main"

[tool.setuptools.packages.find]
where = ["src"]
include = ["nsls2ptycho*"]


